-- Supabase schema for StopAlert Premium

-- User profiles (auto-created by Supabase Auth)
-- auth.users table already exists

-- Tracking data per user
create table if not exists tracking_data (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  progress integer default 0,
  radius integer default 500,
  remaining_distance double precision default 0,
  eta_minutes integer default 0,
  is_approaching boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(user_id)
);

-- Stop preferences per user
create table if not exists stop_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  stop_name text not null,
  stop_lat double precision,
  stop_lng double precision,
  radius integer default 500,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Alert history per user
create table if not exists alert_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  stop_name text not null,
  distance double precision,
  eta_minutes integer,
  triggered_at timestamp with time zone default now()
);

-- Enable Row Level Security
alter table tracking_data enable row level security;
alter table stop_preferences enable row level security;
alter table alert_history enable row level security;

-- Policies: users can only read/write their own data
create policy "Users can read own tracking data"
  on tracking_data for select
  using (auth.uid() = user_id);

create policy "Users can update own tracking data"
  on tracking_data for update
  using (auth.uid() = user_id);

create policy "Users can insert own tracking data"
  on tracking_data for insert
  with check (auth.uid() = user_id);

create policy "Users can read own stop preferences"
  on stop_preferences for select
  using (auth.uid() = user_id);

create policy "Users can update own stop preferences"
  on stop_preferences for update
  using (auth.uid() = user_id);

create policy "Users can insert own stop preferences"
  on stop_preferences for insert
  with check (auth.uid() = user_id);

create policy "Users can read own alert history"
  on alert_history for select
  using (auth.uid() = user_id);

create policy "Users can insert own alert history"
  on alert_history for insert
  with check (auth.uid() = user_id);